// Command preflight adapts the Platform Planning Gateway to black-box agents
// (GitHub Copilot, Cursor) that cannot call the gateway from inside their
// loop: it fetches the amplifier context for an intent and writes it as local
// instruction files the tools read natively.
//
// Usage:
//
//	go run ./adapters/preflight "add the Seka payment method to checkout"
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
)

const gatewayURL = "http://localhost:8000"

func main() {
	if len(os.Args) < 2 {
		log.Fatal(`usage: preflight "<intent>"`)
	}
	intent := os.Args[1]

	body, _ := json.Marshal(map[string]any{
		"intent": intent,
		"repository_context": map[string]any{
			"name":       "checkout-service",
			"tech_stack": []string{"Go"},
		},
	})
	resp, err := http.Post(gatewayURL+"/enrich", "application/json", bytes.NewReader(body))
	if err != nil {
		log.Fatalf("calling the gateway: %v", err)
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	var enriched struct {
		AmplifierContext struct {
			ArchitecturalInvariants []struct {
				ADRID     string `json:"adr_id"`
				Invariant string `json:"invariant"`
			} `json:"architectural_invariants"`
		} `json:"amplifier_context"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&enriched); err != nil {
		log.Fatalf("decoding the gateway response: %v", err)
	}

	var buf bytes.Buffer
	buf.WriteString("# Platform context (generated by the Platform Planning Gateway)\n\n")
	buf.WriteString("Intent: " + intent + "\n\n")
	for _, inv := range enriched.AmplifierContext.ArchitecturalInvariants {
		fmt.Fprintf(&buf, "## %s\n\n%s\n\n", inv.ADRID, inv.Invariant)
	}

	for _, target := range []string{".cursorrules", filepath.Join(".github", "copilot-instructions.md")} {
		if dir := filepath.Dir(target); dir != "." {
			if err := os.MkdirAll(dir, 0o755); err != nil {
				log.Fatal(err)
			}
		}
		if err := os.WriteFile(target, buf.Bytes(), 0o644); err != nil {
			log.Fatal(err)
		}
		fmt.Println("platform context written to", target)
	}
}
