// Command preflight adapts the Platform Planning Gateway to black-box agents
// (GitHub Copilot, Cursor) that cannot call the gateway from inside their
// loop: it fetches the amplifier context for an intent and writes it as local
// instruction files the tools read natively.
//
// Usage:
//
//	go run ./adapters/preflight [-repo <name>] [-stack Go,SQL] "add the Seka payment method to checkout"
//
// The gateway URL is read from the PPG_URL environment variable and defaults
// to http://localhost:8765 (same convention as the Claude Code MCP server).
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

func gatewayURL() string {
	if u := os.Getenv("PPG_URL"); u != "" {
		return u
	}
	return "http://localhost:8765"
}

func main() {
	repo := flag.String("repo", "checkout-service", "repository name sent as repository_context.name")
	stack := flag.String("stack", "Go", "comma-separated tech stack sent as repository_context.tech_stack")
	flag.Parse()

	if flag.NArg() < 1 {
		log.Fatal(`usage: preflight [-repo <name>] [-stack Go,SQL] "<intent>"`)
	}
	intent := flag.Arg(0)

	var techStack []string
	for _, t := range strings.Split(*stack, ",") {
		if t = strings.TrimSpace(t); t != "" {
			techStack = append(techStack, t)
		}
	}

	body, _ := json.Marshal(map[string]any{
		"intent": intent,
		"repository_context": map[string]any{
			"name":       *repo,
			"tech_stack": techStack,
		},
	})
	resp, err := http.Post(gatewayURL()+"/enrich", "application/json", bytes.NewReader(body))
	if err != nil {
		log.Fatalf("calling the gateway: %v", err)
	}
	defer func() {
		_ = resp.Body.Close()
	}()

	var enriched struct {
		AmplifierContext struct {
			ArchitecturalInvariants []struct {
				ADRID     string `json:"adr_id"`
				Invariant string `json:"invariant"`
			} `json:"architectural_invariants"`
		} `json:"amplifier_context"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&enriched); err != nil {
		log.Fatalf("decoding the gateway response: %v", err)
	}

	var buf bytes.Buffer
	buf.WriteString("# Platform context (generated by the Platform Planning Gateway)\n\n")
	buf.WriteString("Intent: " + intent + "\n\n")
	for _, inv := range enriched.AmplifierContext.ArchitecturalInvariants {
		fmt.Fprintf(&buf, "## %s\n\n%s\n\n", inv.ADRID, inv.Invariant)
	}

	for _, target := range []string{".cursorrules", filepath.Join(".github", "copilot-instructions.md")} {
		if dir := filepath.Dir(target); dir != "." {
			if err := os.MkdirAll(dir, 0o755); err != nil {
				log.Fatal(err)
			}
		}
		if err := os.WriteFile(target, buf.Bytes(), 0o644); err != nil {
			log.Fatal(err)
		}
		fmt.Println("platform context written to", target)
	}
}
